# Source contracts for autodiscovery-sources
# Each item defines a source with discovery rules

- key: "bcra_series"
  start_urls:
    - "https://www.bcra.gob.ar/PublicacionesEstadisticas/Informe_monetario_diario.asp"
    - "https://www.bcra.gob.ar/PublicacionesEstadisticas/Principales_variables.asp"
  scope:
    allow_domains: ["bcra.gob.ar"]
    allow_paths_any: ["/Pdfs/PublicacionesEstadisticas", "/PublicacionesEstadisticas"]
    max_depth: 1
    max_candidates: 10
  find:
    link_text_any: ["series", "variables", "xlsm"]
    url_tokens_any: ["series", "PublicacionesEstadisticas"]
  match:
    kind: "regex_any"
    patterns:
      - "(?i)series(.*)\\.xlsm$"
  select:
    prefer_ext: [".xlsm", ".xlsx", ".xls"]
    prefer_newest_by: "last_modified"
  expect:
    mime_any: ["application/vnd.ms-excel.sheet.macroEnabled.12", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
    min_size_kb: 100
  versioning: "date_today"
  mirror: true

- key: "bcra_infomodia_xls"
  start_urls: ["https://www.bcra.gob.ar/PublicacionesEstadisticas/Informe_monetario_diario.asp"]
  scope:
    allow_domains: ["bcra.gob.ar"]
    allow_paths_any: ["/Pdfs/PublicacionesEstadisticas", "/PublicacionesEstadisticas"]
    max_depth: 1
    max_candidates: 2
  find:
    link_text_any: ["infomondia", "informe monetario", "xls"]
    url_tokens_any: ["infomondia", "infomodia"]
  match:
    kind: "regex_any"
    patterns:
      - "(?i)infomodia-(\\d{4}-\\d{2}-\\d{2})\\.xls$"
      - "(?i)informe[_-]?monetario[_-]?diario-(\\d{4}-\\d{2}-\\d{2})\\.xls$"
      - "(?i)infomondia\\.xls$"
  select:
    prefer_ext: [".xls", ".xlsx"]
    prefer_newest_by: "date_from_filename_or_last_modified"
  expect:
    mime_any: ["application/vnd.ms-excel", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"]
    min_size_kb: 60
  versioning: "date_from_filename_or_last_modified"
  mirror: true

- key: "bcra_rem_pdf"
  start_urls: ["https://www.bcra.gob.ar/PublicacionesEstadisticas/Relevamiento_Expectativas_de_Mercado.asp"]
  scope:
    allow_domains: ["bcra.gob.ar"]
    max_depth: 2
    max_candidates: 1
  find:
    link_text_any: ["REM", "Resultados", "pdf"]
    url_tokens_any: ["REM", "PublicacionesEstadisticas"]
  match:
    kind: "regex_any"
    patterns:
      - "(?i)REM\\d{6,8}.*Resultados.*\\.pdf$"
      - "(?i)relevamiento.*mercado.*(\\w+)[-_ ](\\d{4})\\.pdf$"
  select:
    prefer_ext: [".pdf"]
    prefer_newest_by: "best_effort_date_or_last_modified"
  expect:
    mime_any: ["application/pdf"]
    min_size_kb: 200
  versioning: "best_effort_date_or_last_modified"
  mirror: true

- key: "bcra_rem_xlsx"
  start_urls: ["https://www.bcra.gob.ar/PublicacionesEstadisticas/Relevamiento_Expectativas_de_Mercado.asp"]
  scope:
    allow_domains: ["bcra.gob.ar"]
    max_depth: 2
    max_candidates: 5
  find:
    link_text_any: ["REM", "Ranking", "Resultados", "Tablas", "xlsx", "históricos", "historico"]
    url_tokens_any: ["ranking", "tablas", "relevamiento", "expectativas", "historico"]
  match:
    kind: "regex_any"
    patterns:
      - "(?i)ranking.*relevamiento.*expectativas.*\\.xlsx$"
      - "(?i)tablas.*relevamiento.*expectativas.*\\.xlsx$"
      - "(?i)historico.*relevamiento.*expectativas.*\\.xlsx$"
      - "(?i)REM.*Tablas.*\\.xlsx$"
  select:
    prefer_ext: [".xlsx", ".xls"]
    prefer_newest_by: "best_effort_date_or_last_modified"
  expect:
    mime_any: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "application/vnd.ms-excel"]
    min_size_kb: 80
  versioning: "best_effort_date_or_last_modified"
  mirror: true

# API-first → no crawl
- key: "indec_emae_api"
  source_type: "api"
  endpoint: "https://apis.datos.gob.ar/series/api/series?ids=173.1_EMAE_2016_M_19"
  headers:
    Accept-Language: "es-AR"
    User-Agent: "RadarAutodiscovery/1.0"
  versioning: "none"
  mirror: false


